version: '2'

services:
    ask-around:
        container_name: ask-around
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:8080"
        networks:
            - ask-around-network
    mongo-db:
        container_name: mongo-db
        image: mongo
        volumes:
          - ./database:/data/db
        ports:
            - "27017:27017"
        networks:
            - ask-around-network

networks:
    ask-around-network:
        driver: bridge